apiVersion: v1
kind: Service
metadata:
  name: zoo-bridge
  namespace: zoo-bridge
  labels:
    app.kubernetes.io/name: zoo-bridge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zoo-bridge
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
